### ISSUE TITLE
Fix latex codes for the mathematical unicode range

### ISSUE THREAD

**Issue by mathijshenquet** [digitalheir/mathy-unicode-characters#18]
Many characters in [the matematical alphanumeric range](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols#Unicode_chart) contain non standard LaTeX codes. Examples are [\mathsl instead of \mathit](https://digitalheir.github.io/mathy-unicode-characters/?q=\mathsl) for italic, and \mathbit instead of \mathbfit for bold italic.

* The [unicode-math](https://www.ctan.org/pkg/unicode-math) package defines many of these names in a systemetic way. 
* The [isomath](http://ctan.triasinformatica.nl/help/Catalogue/entries/isomath.html) defines some fonts but with a slightly different naming convention (it places sf before bf) as unicode-math.

I suggest we try to keep in line with the general consensus for naming these styles.

**Comment by digitalheir** [comment]
hey nerd good point.

Again I do not understand why you rather make a destructive edit and not just have multiple alternative with the preferred alternative a higher precedence?
